### Three powerful packages
- Numpy
- Pandas
- Matplotlib

## Numpy

- Used for scientific computing
- Helps to create/ manage N-dimensional array

In [185]:
import numpy as np #importing numpy package

In [186]:
x = np.array([1,2,3,4]) #creating numpy array from list

In [187]:
print(x)

[1 2 3 4]


In [188]:
print(type(x))

<class 'numpy.ndarray'>


In [189]:
print(x.shape) #printing the dimensoin of the array

(4,)


In [190]:
y = np.array([[1,2,3],[3,4,8]])

In [191]:
print(y)


[[1 2 3]
 [3 4 8]]


In [192]:
print(y.shape)

(2, 3)


In [193]:
z = np.array([[1+0.j,2+5.j]])  #printing the dimension of the numpy array

In [194]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [195]:
a = np.zeros((2,3)) #creating numpy array of zeros , of dimension (2,3)

In [196]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [197]:
print(a.shape)

(2, 3)


In [198]:
b = np.ones((2,3), dtype=int) #creating numpy array of ones , of dimension (2,3) and integer type

In [199]:
print(b)

[[1 1 1]
 [1 1 1]]


In [200]:
d = np.eye(3) ## identity matrix

In [201]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [202]:
e = np.arange(10) ##similar to Range function

In [203]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [204]:
e = np.arange(12, 21)
print(e)

[12 13 14 15 16 17 18 19 20]


In [205]:
e = np.arange(5,20,3)
print(e)

[ 5  8 11 14 17]


In [206]:
f = np.linspace(1,20,5) ## It create intervals

In [207]:
print(f)

[ 1.    5.75 10.5  15.25 20.  ]


In [208]:
g = np.random.random((3,4))

In [209]:
print(g)

[[0.82311571 0.73743228 0.64721669 0.54649699]
 [0.6762301  0.27159407 0.9115615  0.91725978]
 [0.51596537 0.28057565 0.43032202 0.87289527]]


In [210]:
h = np.random.random((3,4)) #creating a numpy array having dimension (3,4) with random elements

In [211]:
print(h.reshape(2,2,3)) #reshaping the (3,4) array to (2,2,3)

[[[0.52180596 0.26075368 0.39201154]
  [0.29252929 0.75727191 0.68721674]]

 [[0.61906047 0.80848256 0.2515569 ]
  [0.16561747 0.50252279 0.56043835]]]


In [212]:
x = np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [213]:
print(x[-1])

11


In [214]:
x.resize(3,4)

In [215]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [216]:
print(x[-1,-1])

11


In [217]:
print(x[2][3])

11


In [218]:
y = np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [219]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [220]:
print(y[10:15])

[11 12 13 14 15]


In [221]:
print(y[-5:])

[21 22 23 24 25]


In [222]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [223]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [224]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [225]:
y = y.reshape((5,5))
#print(y)
print(y[:4,:4])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


In [226]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [227]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [228]:
print(y[:,-1])

[ 5 10 15 20 25]


In [229]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [230]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [231]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [232]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [233]:
print(a>3)

[False False False  True  True]


In [234]:
a = np.arange(0,4).reshape((2,2))
print(a)

[[0 1]
 [2 3]]


In [235]:
b = np.eye(2)
print(b)

[[1. 0.]
 [0. 1.]]


In [236]:
print(a*b) ##Wrong

[[0. 0.]
 [0. 3.]]


In [237]:
print(np.dot(a,b)) ##Matrix multiplication

[[0. 1.]
 [2. 3.]]


In [238]:
x = np.arange(1,10).reshape(3,3)

In [239]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [240]:
print(x.sum())

45


In [241]:
print(x.sum(axis=0))

[12 15 18]


In [242]:
print(x.sum(axis=1))

[ 6 15 24]


In [243]:
#print(x.sum(axis=2))

In [244]:
x = np.arange(1,19).reshape(3,3,2)
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [245]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [246]:
x = np.arange(1,10).reshape(3,3)

In [247]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [248]:
print(x.max(axis=0))

[7 8 9]


In [249]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [250]:
#print(np.linalg.inv(x))

In [251]:
x = np.arange(1,5).reshape(2,2)
print(np.linalg.inv(x))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [252]:
# prompt: aritematic expression in string  evaluation by input

import numpy as np

def evaluate_expression(expression):
    """Evaluates an arithmetic expression provided as a string.

    Args:
    expression: The arithmetic expression to evaluate.

    Returns:
    The result of the evaluation, or an error message if the expression is invalid.
    """
    try:
        result = eval(expression)
        return result
    except (SyntaxError, NameError, TypeError):
        return "Invalid expression"


if __name__ == "__main__":
    expression = input("Enter an arithmetic expression: ")
    result = evaluate_expression(expression)
    print(f"Result: {result}")

Enter an arithmetic expression: 4=2
Result: Invalid expression


In [253]:
# prompt: store the details of employees and show it in ascending order of their name

employee_details = []

while True:
    name = input("Enter employee name (or type 'done' to finish): ")
    if name.lower() == 'done':
        break

    try:
        age = int(input("Enter employee age: "))
        salary = float(input("Enter employee salary: "))
    except ValueError:
        print("Invalid input. Please enter numeric values for age and salary.")
        continue

    employee_details.append([name, age, salary])


employee_details.sort()

print("\nEmployee Details (Sorted by Name):")
for emp in employee_details:
    print(f"Name: {emp[0]}, Age: {emp[1]}, Salary: {emp[2]}")
print(employee_details)

Enter employee name (or type 'done' to finish): done

Employee Details (Sorted by Name):
[]


In [254]:
import numpy as np

# Create the matrix
matrix = np.array([[12, 8, 15, 3],
                   [7, 20, 11, 9],
                   [14, 6, 18, 22],
                   [5, 13, 4, 16]])
